const data = [
    "The Milky Way is a barred spiral galaxy that is part of the Local Group of galaxies, which also includes the Andromeda Galaxy, the Triangulum Galaxy, and about 54 other smaller galaxies. It is estimated to contain 100 to 400 billion stars and has a diameter of about 100,000 light-years.",
    "In recent political developments, the leaders of several nations convened for a summit to discuss global economic challenges and climate change. The discussions centered around the need for collaborative efforts to address pressing issues and promote sustainable development.",
    "The Amazon Rainforest, often referred to as the 'lungs of the Earth,' spans over nine countries in South America, including Brazil, Peru, and Colombia. It is home to an incredibly diverse array of flora and fauna, many of which are not found anywhere else on the planet.",
    "Breaking news - Scientists have made a groundbreaking discovery in the field of medical research, unveiling a potential treatment for a previously incurable disease. The research, conducted over several years, offers hope for millions of people affected by this condition.",
    "The latest advancements in artificial intelligence are revolutionizing industries worldwide. From autonomous vehicles to smart home devices, AI is playing a crucial role in shaping the future of technology and improving efficiency across various sectors.",
    "Maintaining a balanced diet and regular exercise are key components of a healthy lifestyle. Incorporating nutrient-rich foods and engaging in physical activity can contribute to overall well-being and reduce the risk of chronic diseases.",
    "The impact of climate change on our planet is becoming increasingly evident. Rising global temperatures, extreme weather events, and melting ice caps are pressing concerns that demand urgent attention and concerted efforts to mitigate their effects.",
    "Our solar system consists of eight planets, with Earth being the third planet from the Sun. Each planet has unique characteristics, and ongoing space exploration missions continue to unveil the mysteries of our cosmic neighborhood.",
    "The geopolitical landscape is constantly evolving, with diplomatic relations, international agreements, and global conflicts shaping the world. Leaders engage in dialogue to address challenges and foster cooperation on the international stage.",
    "The Great Barrier Reef, located off the coast of Australia, is the largest coral reef ecosystem in the world. It is home to a vast array of marine life, including colorful coral formations, diverse fish species, and majestic sea turtles.",
    "Recent developments in technology have sparked debates on ethical considerations surrounding artificial intelligence. As AI continues to advance, discussions on responsible use and potential societal impacts are gaining prominence.",
    "The Internet of Things (IoT) is revolutionizing the way we interact with everyday objects. Smart devices, connected through the internet, enable seamless communication and automation, enhancing efficiency and convenience.",
    "Mental health awareness is a crucial aspect of overall well-being. Initiatives to destigmatize mental health issues and promote access to support services contribute to creating a more compassionate and understanding society.",
    "Deforestation remains a significant environmental concern, impacting biodiversity and contributing to climate change. Conservation efforts and sustainable forestry practices are essential in preserving our planet's vital ecosystems.",
    "Quantum mechanics, a branch of physics, explores the behavior of particles at the smallest scales. Concepts like superposition and entanglement challenge our classical understanding of the physical world.",
    "The Olympic Games, held every four years, bring together athletes from around the world to compete in various sports. The event fosters international camaraderie and showcases exceptional athleticism on a global stage.",
    "The Renaissance was a period of cultural and intellectual flourishing in Europe, marked by advancements in art, literature, and scientific inquiry. It laid the groundwork for the profound changes that shaped the modern world.",
    "Economic indicators, such as GDP and unemployment rates, offer insights into the health of a nation's economy. Policymakers use this data to formulate strategies for economic growth and stability.",
    "Urgent action is needed to address the accelerating effects of climate change. Rising sea levels, extreme weather events, and disruptions to ecosystems underscore the critical importance of global collaboration in mitigating environmental threats.",
    "As humanity looks beyond our own planet, space agencies are planning ambitious missions to explore Mars and distant celestial bodies. The quest for knowledge drives our exploration of the cosmos.",
    "The Hubble Space Telescope has been instrumental in capturing breathtaking images of distant galaxies, nebulae, and other celestial phenomena. Its contributions to our understanding of the cosmos have been invaluable to astronomers and researchers worldwide.",
    "Recent political developments have sparked debates on global governance and international relations. Issues such as trade agreements, diplomatic tensions, and human rights violations are at the forefront of discussions among world leaders and policymakers.",
    "The Great Barrier Reef, located off the coast of Australia, is the world's largest coral reef system. It is a UNESCO World Heritage site and is home to a diverse ecosystem of marine life, including vibrant coral formations, fish species, and marine turtles.",
    "In the realm of technology, major companies are racing to develop innovative solutions for sustainable energy and environmental conservation. Advancements in green technology aim to address climate change and reduce the ecological footprint of human activities.",
    "The field of robotics is witnessing remarkable progress with the development of humanoid robots capable of intricate tasks. From assisting in healthcare to performing complex manufacturing processes, these robots are revolutionizing various industries.",
    "Mental health awareness is gaining prominence as societies recognize the importance of emotional well-being. Initiatives promoting mental health education and destigmatizing mental health issues aim to create a more supportive and understanding environment.",
    "The study of genetics has opened new frontiers in medicine, allowing for personalized treatments and targeted therapies. Advances in gene editing technologies offer potential breakthroughs in the treatment of genetic disorders and certain types of cancer.",
    "The Renaissance, a period of cultural and intellectual rebirth in Europe, marked a significant era of innovation in art, science, and philosophy. It laid the foundation for the modern world and influenced the course of human history for centuries to come.",
    "As climate change intensifies, the need for sustainable practices becomes increasingly urgent. From renewable energy sources to eco-friendly transportation, individuals and businesses alike play a crucial role in mitigating the impact of climate change.",
    "The Olympic Games, a global sporting event held every four years, bring together athletes from around the world to compete in a spirit of camaraderie and excellence. The games showcase athletic prowess and serve as a platform for cultural exchange.",
    "Exploring diverse landscapes and experiencing different cultures enriches our understanding of the world. Whether it's trekking through lush rainforests, visiting historical landmarks, or immersing oneself in local traditions, travel broadens perspectives.",
];

export const getText = () => {
    const randomIndex = Math.floor(Math.random() * data.length);
    return data[randomIndex].split('');
}